### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by desaperados** [vulcanize/VulcanizeDB#1]
Ran into this error when attempting to run `godo vulcanizeDb -- --environment=ethlive` against an empty postgresql database and fully fast-synced geth instance:

```
$ godo vulcanizeDb -- --environment=ethlive  
vulcanizeDb 3ms
2018/01/02 15:38:46 SubscribeToBlocks
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7ebbcb]

goroutine 1 [running]:
github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/core/types.(*Block).Transactions(...)
        /home/maker/go/src/github.com/vulcanize/vulcanizedb/vendor/github.com/ethereum/go-ethereum/core/types/block.go:293
github.com/vulcanize/vulcanizedb/pkg/geth.GethBlockToCoreBlock(0x0, 0xe39340, 0xc42000e248, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/maker/go/src/github.com/vulcanize/vulcanizedb/pkg/geth/geth_block_to_core_block.go:19 +0x8b
github.com/vulcanize/vulcanizedb/pkg/geth.(*GethBlockchain).GetBlockByNumber(0xc42006de40, 0xffffffffffffffe6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/maker/go/src/github.com/vulcanize/vulcanizedb/pkg/geth/geth_blockchain.go:50 +0xe5
github.com/vulcanize/vulcanizedb/pkg/history.updateBlockRange(0xe42f20, 0xc42006de40, 0xe435a0, 0xc420188900, 0xc4201d0000, 0x18, 0x18, 0xc420103dc0)
        /home/maker/go/src/github.com/vulcanize/vulcanizedb/pkg/history/populate_blocks.go:35 +0x8d
github.com/vulcanize/vulcanizedb/pkg/history.UpdateBlocksWindow(0xe42f20, 0xc42006de40, 0xe435a0, 0xc420188900, 0x18, 0xc420186000, 0xc420186100, 0xc420000208)
        /home/maker/go/src/github.com/vulcanize/vulcanizedb/pkg/history/populate_blocks.go:29 +0xd5
main.validateBlocks(0xc42006de40, 0xc42015b8f0, 0xc42001cd70, 0x42, 0x3ff0000000000000, 0x1, 0x18, 0xc420196040)
        /home/maker/go/src/github.com/vulcanize/vulcanizedb/cmd/vulcanize_db/main.go:42 +0xa0
main.main()
        /home/maker/go/src/github.com/vulcanize/vulcanizedb/cmd/vulcanize_db/main.go:67 +0x49f
exit status 2
```

Here's the `ethlive.toml`:

```
[database]
name = "vulcanize_ethlive"
host = "localhost"
port = 5432

[client]
ipcPath = "/home/maker/.ethereum/geth.ipc"
```
(`godo run -- --environment=ethlive` is working without any issue)

NixOS 17.09
Geth Version: 1.7.3-stable
Postgresql 10.0
Go 1.9.2 linux/amd64

**Comment by AFDudley** [comment]
There is a "new" version in the repo can you please see if you're still getting the error? Thanks.

**Comment by desaperados** [comment]
no error with this version of the repo - thanks :-)
